{% set name = "datetime-distance" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datetime-distance-{{ version }}.tar.gz
  sha256: 7177a54a3555d4737626786f70a062e509f7c0014ba63fc26cd28263b8c64d68

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - future
    - python >={{ python_min }}
    - python-dateutil >=2.6.0

test:
  imports:
    - datetime_distance
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dedupeio/datetime-distance
  summary: Compare string distances between dates, timestamps, or datetime objects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
